AllCops:
  Exclude:
  - spec/**/*
  - coverage/**/*
  - lib/generators/sail/install/templates/**/*

Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
# Disabled because we want to support
# versions of Ruby < 2.5.0
Style/RedundantBegin:
  Enabled: false
