AllCops:
  Exclude:
  - spec/**/*
  - coverage/**/*
  - lib/generators/sail/install/templates/**/*

Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
