AllCops:
  Exclude:
  - spec/**/*
  - coverage/**/*
  - lib/generators/sail/install/templates/**/*

Metrics/LineLength:
  Max: 140
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/StringLiterals:
  Enabled: false
